# Generated by Django 4.0.5 on 2022-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparteman',
            name='andaze',
            field=models.PositiveSmallIntegerField(verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='vilae',
            name='gheymat',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='zamin',
            name='andaze',
            field=models.PositiveSmallIntegerField(verbose_name=' اندازه'),
        ),
    ]
